apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: hello-world
  endpoints:
  - port: metrics
    interval: 5s
